---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/data/settings.json
  label: Settings
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/index.md"
  new_doc_ext: md
  templates:
  - page
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: npm run forestry:preview
  publish_command: gatsby build
  preview_output_directory: public
  output_directory: public
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
